# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оставленного комментария'),
        ),
    ]
