# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0003_comment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='images/events_calendar/default.png', upload_to='images/events_calendar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='images/users/default.png', upload_to='images/users'),
        ),
    ]
