# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 15:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0004_auto_20170730_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('image', models.ImageField(blank=True, default='images/organization/default.png', upload_to='images/organization')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Organization', verbose_name='Организация'),
        ),
    ]
