# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0005_auto_20170804_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Organization', verbose_name='Организация'),
        ),
    ]
