# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0006_auto_20170804_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, default='images/organization/default.jpg', upload_to='images/organization'),
        ),
    ]
