# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0007_auto_20170806_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='signed_organizations',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='events_calendar.Organization', verbose_name='Организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='events_calendar.Organization', verbose_name='Организация'),
        ),
    ]
