# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 18:44
from __future__ import unicode_literals

import cuser.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events_calendar', '0010_auto_20170820_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(blank=True, default='images/events_calendar/default.jpg', upload_to='images/events_calendar')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('place_of_event', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место события')),
                ('vk_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка в Вк')),
                ('fb_link', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ссылка в Фэйсбук')),
                ('published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Category', verbose_name='Категория')),
                ('creator', cuser.fields.CurrentUserField(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Event_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
                'ordering': ['start_date'],
            },
        ),
    ]
