# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0011_proposedevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposedevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Предложенное Событие', 'verbose_name_plural': 'Предложка'},
        ),
        migrations.AddField(
            model_name='organization',
            name='access_to_the_offer',
            field=models.BooleanField(default=False),
        ),
    ]
