# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-17 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0012_auto_20170829_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категорія', 'verbose_name_plural': 'Категорії'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментар', 'verbose_name_plural': 'Коменти'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-start_date'], 'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профіль', 'verbose_name_plural': 'Профілі'},
        ),
        migrations.AlterModelOptions(
            name='proposedevent',
            options={'ordering': ['start_date'], 'verbose_name': 'Запропонована подія', 'verbose_name_plural': 'Предложка'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Event', verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(verbose_name='Коментар'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата залишеного коментаря'),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Organization', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fb_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання в fb'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='event',
            name='place_of_event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місце події'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='event',
            name='vk_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання в Вк'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Найменування'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='events_calendar.Organization', verbose_name='Організація'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='signed_organizations',
            field=models.ManyToManyField(blank=True, related_name='organizations', to='events_calendar.Organization', verbose_name='Організації'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events_calendar.Category', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='description',
            field=models.TextField(verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата закінчення'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='fb_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання в Фэйсбук'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Назва'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='place_of_event',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Місце події'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Опублікований'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='start_date',
            field=models.DateTimeField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='vk_link',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання в Вк'),
        ),
    ]
