# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0015_auto_20170917_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='proposedevent',
            name='description',
            field=models.TextField(null=True, verbose_name='Опис'),
        ),
    ]
