# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0017_auto_20171005_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='web_site',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Посилання на сайт події'),
        ),
    ]
