# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_calendar', '0019_auto_20171007_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='vk_link',
        ),
    ]
